<script>
    import {parseCurrency} from "../../../common/parse_currency"
    import Heading from "../../../component/Heading.svelte";
    export let data;
    console.log(data)

    let totalUser = "loading...";
    let activatedUser = "loading...";
    let totalDeposit = "loading...";
    let totalWithdrawal = "loading...";
    let depositAmount = "loading...";
    let withdrawAmount = "loading...";

    if (data){
        totalUser = data.totalUser;
        activatedUser = data.totalActivatedUser;
        totalDeposit = data.totalDeposit;
        totalWithdrawal = data.totalWithdrawal;
        depositAmount = data.totalDepositAmount;
        withdrawAmount = data.totalWithdrawalAmount;
    }

</script>

<div class="container">
    <p class="heading">Monthly Statistics</p>
    <p class="monthly-sub">Notes: Value is not generated by real-time data
        refresh to get the newest data</p>
    <div class="monthly-container">
        <div class="monthly-item">
            <p>Total Users</p>
            <p>{totalUser}</p>
        </div>
        <div class="monthly-item">
            <p>Activated Users</p>
            <p>{activatedUser}</p>
        </div>
        <div class="monthly-item">
            <p>Total Deposit</p>
            <p>{totalDeposit}</p>
        </div>
        <div class="monthly-item">
            <p>Total Withdrawal</p>
            <p>{totalWithdrawal}</p>
        </div>
        <div class="monthly-item">
            <p>Total Deposit Amount</p>
            <p>{parseCurrency(depositAmount)}</p>
        </div>
        <div class="monthly-item">
            <p>Total Withdrawal Amount</p>
            <p>{parseCurrency(withdrawAmount)}</p>
        </div>
    </div>
</div>

<style>
    p{
        margin: unset;
    }

    .monthly-container{
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 20px;
    }

    .monthly-item{
        background-color: whitesmoke;
        font-size: 13px;
        padding: 20px;
        border-radius: 10px;
    }

    .monthly-item > p{
        margin-bottom: 10px;
    }

    .monthly-sub{
        text-align: center;
        color: var(--text-color);
    }
</style>